[package]
name = "akaza-make-system-lm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libakaza = { path = "../../libakaza" }
