[package]
name = "akaza-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libakaza = { path = "../../libakaza" }
env_logger = "0.10.0"
tempfile = "3"
log = "0.4.17"
