# TODO: make data and commit & push.
name: Akaza data building test

on:
  schedule:
    - cron: '20 20 20 * *'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install kytea
      run: |
        # Note: Cannot compile kytea 0.4.7 on latest ubuntu.
        # We need to use git HEAD now.
        sudo apt-get install autoconf
        git clone https://github.com/neubig/kytea.git
        cd kytea && autoreconf -i && ./configure --prefix=/usr && make && sudo make install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r akaza-data/requirements.txt
        pip install flake8 pytest
        sudo apt-get update
        sudo apt-get install ibus libgirepository1.0-dev libmarisa-dev cmake
    - name: Test akaza-data
      run: |
        cd akaza-data
        make
        pip install -r requirements.txt
        make
    - name: Commit
      run: |
        git config --global user.email "tokuhriom@gmail.com"
        git config --global user.name "tokuhirom by github actions"
        git diff --quiet && git diff --staged --quiet || git commit -a -m 'Update dictionary'
    - name: push
      run: git push origin master
    - name: Check result
      run: |
        make check
