name: Akaza basic test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ibus libgirepository1.0-dev libmarisa-dev clang libibus-1.0-dev unzip libgtk-4-dev
    - name: make test data
      run: |
        cd akaza-data/ && make test-data
    - name: make some configuration files for ibus-akaza
      run: |
        cd ibus-akaza/ && make
    - uses: dtolnay/rust-toolchain@stable
      with:
          components: clippy, rustfmt
    - run: cargo fmt --all --check
    - run: cargo clippy -- -D warnings
    - run: cargo test
    - run: cargo install --locked cargo-deny
    - run: cargo deny check

