name: Akaza basic test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ibus libgirepository1.0-dev libmarisa-dev cmake clang libibus-1.0-dev
    - name: make test data
      run: |
        cd akaza-data/ && make test-data
    - name: make some configuration files for ibus-akaza
      run: |
        cd ibus-akaza/ && make
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - uses: actions-rs/cargo@v1
      with:
        command: test

