name: Generate the model file

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          akaza-data/work/jawiki/jawiki-latest-pages-articles.xml.bz2
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ibus libgirepository1.0-dev libmarisa-dev clang libibus-1.0-dev unzip
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install wikiextractor
    - uses: dtolnay/rust-toolchain@stable
    - name: make some configuration files for ibus-akaza
      run: |
        cd ibus-akaza/ && make
    - name: download wikipedia data
      run: |
        cd akaza-data/ && make work/jawiki/jawiki-latest-pages-articles.xml.bz2
    - name: make data
      run: |
        cd akaza-data/ && make all
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -D warnings
    # model を利用した integration test を実施する
    - run: cargo test --all-features
    - name: evaluate the model
      run: |
        cd akaza-data/ && make evaluate
    - name: Create model package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd akaza-data/data/ && tar czvf ../../akaza-data.tar.gz ./*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: akaza-data.tar.gz
        generate_release_notes: true

