name: Generate the model file

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          akaza-data/work/jawiki/jawiki-latest-pages-articles.xml.bz2
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ibus libgirepository1.0-dev libmarisa-dev clang libibus-1.0-dev
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install wikiextractor
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: make some configuration files for ibus-akaza
      run: |
        cd ibus-akaza/ && make
    - uses: actions-rs/toolchain@v1
    - name: download wikipedia data
      run: |
        cd akaza-data/ && make work/jawiki/jawiki-latest-pages-articles.xml.bz2
    - name: make data
      run: |
        cd akaza-data/ && make all
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    # model を利用した integration test を実施する
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features it
    - name: evaluate the model
      run: |
        cd akaza-data/ && make evaluate
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: gz
        GHR_PATH: akaza-data/data/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

